### ISSUE TITLE
Need to replace PyPI's XML-RPC .top_packages()

### ISSUE THREAD

**Issue by cclauss** [cclauss/python3wos_asyncio#9]
Follow the advise in https://github.com/pypa/warehouse/issues/1930 to use a modification of https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/cloud-client/async_query.py to execute a query based on https://langui.sh/2016/12/09/data-driven-decisions/ (_Query: Most Popular Projects_) to deliver a replacement for the no longer updated PyPI's XML-RPC .top_packages().

**Comment by cclauss** [comment]
@hugovk  I am wondering if you would be interested to help me...

As you know, http://python3wos.appspot.com is rapidly reaching its EOL and its maintainer is not excited to add new functionality.  It is based on a static list of top 100 packages which has not changed in for a long time.  The MOZ guys hope [fix their remaining packages this month](https://bugzilla.mozilla.org/show_bug.cgi?id=1093212#c26).

I have used [GitHub Trending Python](https://github.com/trending/python) to give me fresh targets to convert to Python 3 but 1) that is only 10 packages at a time and 2) GitHub stars are a bit of a subjective measure of a package's success.  I use [itinerant-tester](https://github.com/cclauss/itinerant-tester) to find package that have Python3 compatibility issues and [itinerant-futurizer](https://github.com/cclauss/itinerant-futurizer) to create PRs to address those issues.

I believe that https://github.com/cclauss/python3wos_asyncio/blob/master/bigquery_pypi.py represents the best way to measure which Python packages are __currently__ most important.  It would be possible to use that query to drive a modern replacement for WoS and http://py3readiness.org  Given your passion for getting the community to Python 3, you might be an ideal collaborator for stitching this all together.  Thoughts?

**Comment by hugovk** [comment]
Looks good.

I've done something similar for https://github.com/hugovk/drop-python/, which is forked from https://github.com/meshy/pythonwheels.

That uses an offline dump of packages, created using https://github.com/ofek/pypinfo. I've just updated the dump, see https://github.com/hugovk/drop-python/pull/14 for details.

The query is essentially the same as in https://github.com/cclauss/python3wos_asyncio/blob/master/bigquery_pypi.py (except for a year instead of a month, and 500 packages instead of 5000).

I think the main challenges are having a Google account to run from and staying inside the Big Query quota. The list wouldn't need updating all that regularly. My quota is often at the limit, I calculated you can do something like 3 queries per day of the Python versions of a single package, each costs about 17 GB.

Grabbing downloads for 500 packages is 94 GB, so that could be done about weekly on a dedicated quota. But perhaps monthly may be sufficient.

---

However, I wonder if it's worth extending http://python3wos.appspot.com when there's also https://github.com/chhantyal/py3readiness which does more or less the same thing? Would it be better to extend that?

In any case, having a regularly updated pypi_packages.json on the net would be useful for 
all of pythonwheels, py3readiness, drop-python, python3wos* and anything else (re: https://github.com/meshy/pythonwheels/issues/94, https://github.com/chhantyal/py3readiness/issues/42).

**Comment by cclauss** [comment]
OK...  What if once a week you did Python packages 1-500 with your account and I did Python packages 501-1000 with my account.  We put those results into a repo and then updated a single UI to do the top 1000 packages of that week?

**Comment by hugovk** [comment]
I've set up https://github.com/hugovk/top-pypi-packages to automatically fetch the top 1,000 packages once a week. :)

It turned out that getting 500 or 1,000 or 5,000 packages all cost about the same.
* 94,182,047,744 bytes for 500/1,000, 
* 94,314,168,320 bytes for 5,000, 
* all about ~94 GB.

drop-python is now using that: https://github.com/hugovk/drop-python/commit/961c68cfd0e9ee234f40052e6f770621392aa952.

Note they're the top packages over the preceding 365 days. Is that suitable for you?

**Comment by cclauss** [comment]
Sounds really cool.  I will investigate this weekend.  Thanks!

**Comment by cclauss** [comment]
Hi hugovk...

Would it be possible to get a different feed?  Instead of the most downloaded packages of all time, would it be possible to get the most downloaded packages of the past 30 days?  That list might be more topical as well as more dynamic.

Another question: Do you know of a list of the those Linux distros that have gone Python 3 only?  On issue 10 of NullArray/AutoSploit, I listed some info on:
* Ubuntu https://wiki.ubuntu.com/Python and
* Debian https://www.debian.org/releases/stable/amd64/release-notes/ch-whats-new.en.html
but more ammo on this would help push the security scripters to consider Python 3.

**Comment by hugovk** [comment]
It's currently the last 365 days, not all time. But sure, I'll add one for the last 30 days.

Instead of top-pypi-packages.json, shall I call them top-pypi-packages-30-days.json and top-pypi-packages-365-days.json?

I don't know of such a list, perhaps you can find one via DistroWatch.com:

* https://distrowatch.com/table.php?distribution=ubuntu

Or using/modifying one of these tools which scrape it:

* https://github.com/Mariatta/python_versions_and_distros
* https://github.com/mlouielu/python-linux-distro-list

Let me know if you find one :)

**Comment by hugovk** [comment]
There we go!

* https://hugovk.github.io/top-pypi-packages/top-pypi-packages-30-days.json
* https://hugovk.github.io/top-pypi-packages/top-pypi-packages-365-days.json

**Comment by hugovk** [comment]
@cclauss Just to let you know, the JSON structure of https://github.com/hugovk/top-pypi-packages has changed a little bit.

pypinfo from [12.0.0/13.0.0 onwards](https://github.com/ofek/pypinfo#changelog) now has the packages in `'rows'`, there's new metadata about the Google BigQuery in `query`, and a `last_update` UTC timestamp.

It's easy to update: https://github.com/hugovk/drop-python/pull/16/files

**Comment by cclauss** [comment]
Cool.  Thanks for the tip...

The data that I am looking for is:
1. Top packages in last 30 daze in order by number of downloads in last 30 days
2. Number of downloads in last 30 days, not the number of downloads of all time.

**Comment by hugovk** [comment]
Great, that's what you'll find in here: 

https://hugovk.github.io/top-pypi-packages/top-pypi-packages-30-days.json

**Comment by cclauss** [comment]
pip was downloaded 14.9 million times in the last 30 daze?!?

```
{
"last_update": "2018-02-10 09:21:55",
"query": {
"bytes_billed": 0,
"bytes_processed": 0,
"cached": true,
"estimated_cost": "0.00"
},
"rows": [
{
"download_count": 14984694,
"project": "pip"
},
```

**Comment by hugovk** [comment]
Yes!

* 15,539,213 times for the 30 days up to 2018-02-07 ([json](https://github.com/hugovk/top-pypi-packages/blob/48002cebbb7a09509cd71490bfa84f0b19dfc005/top-pypi-packages-30-days.json))
* 14,984,694 times for the 30 days up to 2018-02-10

Note the latter 30 days are a bit lower. If it were all-time, it'd go up.

Also, for the last 365 days, it was 155,470,352, which is about x ~12.

**Comment by cclauss** [comment]
Holy cow!  Massive numbers.  Thanks.  Now I need to get busy...
